version: '3.7'

services:
    apache:
        build:
            context: .
            dockerfile: apache.dockerfile
        image: apache_pb3

    openresty:
        build:
            context: .
            dockerfile: openresty.dockerfile
        image: openresty_pb3