version: '3.7'

x-source-mount:
  &pb-source-mount
    type: bind
    source: .
    target: /var/www/html/website/

services:
    mysqldb:
        image: mysql:5.7
        ports:
            - "3306:3306"
        container_name: mysqldb
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pbox14
        networks:
            - openresty-apache-network

    apache_pb3:
        build:
            context: .
            dockerfile: apache.dockerfile
        image: apache_pb3
        volumes:
            - *pb-source-mount
        networks:
            - openresty-apache-network

    phpfmp_pb3:
        build:
            context: .
            dockerfile: phpfpm.dockerfile
        image: phpfmp_pb3
        volumes:
            - *pb-source-mount
        networks:
            - openresty-apache-network

    openresty_pb3:
        build:
            context: .
            dockerfile: openresty.dockerfile
        image: openresty_pb3
        depends_on:
            - apache_pb3
            - phpfmp_pb3
        volumes:
            - ./nginx-lua/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
            - *pb-source-mount
        networks:
            - openresty-apache-network
        ports:
            - "80:80"

networks:
    openresty-apache-network:
        driver: bridge


#services:
#    apache_pb3:
#        build:
#            context: .
#            dockerfile: apache.dockerfile
#        image: apache_pb3

#    openresty_pb3:
#        build:
#            context: .
#            dockerfile: openresty.dockerfile
#        image: openresty_pb3